project_id = "nkseanjwwpnpfyrlwqwk"

[functions.chat-with-chef]
verify_jwt = false

[functions.analyze-menu]
verify_jwt = false

[functions.generate-recipe]
verify_jwt = false

[functions.generate-shopping-list]
verify_jwt = false