// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkseanjwwpnpfyrlwqwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rc2Vhbmp3d3BucGZ5cmx3cXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4NjQwMjksImV4cCI6MjA1MTQ0MDAyOX0.NcAu7mdDwcKPiicaQRkt_FxDBr0LOHax8WygZAFPk1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);